# The pipeline's dependencies rarely change. Having a separate docker image for testing avoids continuous integration
# from downloading/compiling/installing dependencies every time the pipeline code is modified and committed.

FROM registry.gitlab.com/kuurstra/cfmm-nipype-interfaces:v1-0-0

ENV DEBIAN_FRONTEND=noninteractive

RUN pip install virtualenv

#=============================================
#install fsl
#=============================================
RUN echo "America/New_York" | sudo tee /etc/timezone && sudo dpkg-reconfigure --frontend noninteractive tzdata
RUN wget -O- http://neuro.debian.net/lists/trusty.de-md.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
#sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
RUN apt-key adv --recv-keys --keyserver hkp://ha.pool.sks-keyservers.net 0xA5D32F012649A5A9
RUN sudo apt-get update
RUN sudo apt-get install -y fsl=5.0.9-5~nd14.04+1
#=============================================

#fsl
ENV FSLDIR=/usr/share/fsl/5.0
ENV POSSUMDIR=$FSLDIR
ENV PATH=/usr/lib/fsl/5.0:$PATH
ENV FSLOUTPUTTYPE=NIFTI_GZ
ENV FSLMULTIFILEQUIT=TRUE
ENV FSLTCLSH=/usr/bin/tclsh
ENV FSLWISH=/usr/bin/wish
ENV FSLBROWSER=/etc/alternatives/x-www-browser
ENV LD_LIBRARY_PATH=/usr/lib/fsl/5.0:${LD_LIBRARY_PATH}
